[package]
name = "pinokkio"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
oneshot = { version = "0.1.11", default-features = false }

[features]
timers = []

[dev-dependencies]
futures = { version = "0.3" }
